# Learning Numpy and Pandas for Data Analysis

## Numpy - Numerical Python 
      - structure - Numpy ndimensional 
      - Super fast processing
      - it deals only in numeric values

### Creating a numpy Array 

Dimensional Array

In [2]:
import numpy as np

In [3]:
# using python list
lst = [1,2,3,4,5,6,7,8,9,10]
print(type(lst))
arr1d = np.array(lst)
type(arr1d)

<class 'list'>


numpy.ndarray

In [4]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [11]:
lst * 2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Vectorized Operation
 

In [10]:
arr1d * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [12]:
arr1d/10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [14]:
arr1d +2 

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
arr1d - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [16]:
arr1d % 2

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [18]:
arr1d.size

10

In [19]:
arr1d.ndim

1

In [22]:
arr1d.shape

(10,)

In [23]:
#Using numpy arange
arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
#2dArray from python list
lst2d = [[1,2,3],[11,22,33],[111,222,333]]
lst2d

[[1, 2, 3], [11, 22, 33], [111, 222, 333]]

In [25]:
arr2d = np.array(lst2d)
arr2d

array([[  1,   2,   3],
       [ 11,  22,  33],
       [111, 222, 333]])

In [26]:
arr2d.ndim

2

In [27]:
arr2d.shape

(3, 3)

In [28]:
arr2d = np.arange(36).reshape(4,9)
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [31]:
arr2d = np.arange(36).reshape(9,4)
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [32]:
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr1d[7]

7

In [34]:
arr1d[4:8]

array([4, 5, 6, 7])

In [40]:
arr1d[-1]

9

In [41]:
arr1d[5]

5

In [42]:
arr1d[5:6]

array([5])

In [43]:
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [45]:
arr2d.reshape(4,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [46]:
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [47]:
arr2d = arr2d.reshape(4,9)

In [48]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [49]:
# index value 23 from arr2d
arr2d[2][5]

23

In [50]:
arr2d[2,5]

23

In [51]:
# arr2d[row,col]  >>> [startrow:endrow,statcol:endcol]

arr2d[1:2,2:7]
#Slice

array([[11, 12, 13, 14, 15]])

In [52]:
arr2d[1:3,5:7]

array([[14, 15],
       [23, 24]])

In [53]:
arr2d[0:4, 6:9]

array([[ 6,  7,  8],
       [15, 16, 17],
       [24, 25, 26],
       [33, 34, 35]])

In [54]:
arr2d[:, 6:]

array([[ 6,  7,  8],
       [15, 16, 17],
       [24, 25, 26],
       [33, 34, 35]])

In [57]:
arr2d[2,4:7]


array([22, 23, 24])

In [58]:
arr2d[:,-1]

array([ 8, 17, 26, 35])

In [59]:
arr2d[:,8:]

array([[ 8],
       [17],
       [26],
       [35]])

In [79]:
arr2d[:,::3]

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24],
       [27, 30, 33]])

In [80]:
arr2d[:,::-2]

array([[ 8,  6,  4,  2,  0],
       [17, 15, 13, 11,  9],
       [26, 24, 22, 20, 18],
       [35, 33, 31, 29, 27]])

In [60]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
type(np.arange(10))

numpy.ndarray

In [62]:
np.arange(10).ndim

1

In [63]:
np.arange(10).shape

(10,)

In [64]:
np.arange(10).reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [65]:
type(np.arange(10).reshape(1,10))

numpy.ndarray

In [66]:
np.arange(10).reshape(1,10).ndim

2

In [67]:
np.arange(10).reshape(1,10).shape

(1, 10)

In [75]:
np.array([[19]])

array([[19]])

In [74]:
np.array([[19,1, 2], [4, 5, 6]])

array([[19,  1,  2],
       [ 4,  5,  6]])